name: NLTK Reuters
id: reuters
loader:
  type: parquet
  params: {}
raw:
  paths:
    - data/raw/reuters/reuters_full.parquet
fields:
  id: id
  split: split
  title: null
  text: text
  meta: topics          
splits:
  infer_from: split
preprocess:
  lowercase: true
  normalize_unicode: true
  min_tokens: 10
  drop_duplicates: true
  token_pattern: "[a-zA-Z]+(?:'[a-z]+)?"
  stopwords:
    base: english
    extra: ["reuters","reuter","said","would","also"]
eda:
  top_terms_n: 30
  ner:
    enabled: true
    limit: 2000
    labels: ["PERSON","ORG","GPE","DATE"]
outputs:
  interim: data/interim/reuters/preprocessed.parquet
  processed_dir: data/processed/reuters
  figures_dir: reports/figures
