project_name: escalate-nlp-agent
dataset_config: configs/dataset/reuters.yaml   
paths:
  data_dir: data
  raw_dir: data/raw
  interim_dir: data/interim
  processed_dir: data/processed
  models_dir: models
  reports_dir: reports
dataset: dataset/reuters.yaml          
extract: extract/spacy_ner.yaml        
summarize: summarize/textrank.yaml     
eval: eval/rouge.yaml
agent:
  retriever: tfidf
  use_memory: false
logging:
  level: INFO
  fmt: "[%(asctime)s] %(levelname)s - %(name)s: %(message)s"
project_name: escalate-nlp-agent

logging:
  level: INFO
  fmt: "[%(asctime)s] %(levelname)s - %(name)s: %(message)s"
